### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by shenganzhang** [pyasi/pybuildkite#72]
`tests/test_client.py::TestClientRequest` can fail when running with `pytest --randomly-seed=1234` or `pytest --randomly-seed=123`.

**Comment by jmelahman** [comment]
I don't fully understand how it's leaking (I'm not super familiar with pytest which I think is contributing). I think fundamentally the issue is that `headers` in `client.request()` is default a mutable object, https://medium.com/geekculture/do-not-use-objects-as-default-arguments-in-python-1c940212db2e. Generally, it's better practice to,

```
def request(
    ...
    headers=None
):
    if not headers:
        headers = {}
```
but there's also an explicit assertion that headers is `not None` which I don't have context on. An alternative, test-only fix is to always ensure a `headers={}` is passed as to no mutate the default value.

I will include a fix for the tests in https://github.com/pyasi/pybuildkite/pull/80 as this is blocking that.
